### ISSUE TITLE
Folder name error

### ISSUE THREAD

**Issue by trashIntegral** [Amenly/EroMe#1]
When you download an album with an invalid name for a folder, you get a winerror 267 and the download stops. So you can't download the album itself and you can't download profiles past an album with an invalid name.

**Comment by Amenly** [comment]
I'll get to work on a fix for that. Is there any chance you could send me a link to the specific album that caused the error?

**Comment by trashIntegral** [comment]
For example this one "https://www.erome.com/a/L0qo2QO9", but every album with a ":" in the name does it

**Comment by Amenly** [comment]
Really sorry for the delay--should work now though!
